version: "3.8"

services:
  redis:
    image: redis:7.2.4-alpine
    restart: unless-stopped
    command: >
      redis-server
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --maxmemory-samples 5
    volumes:
      - lanyard_presence_data:/data:rw
    networks:
      - internal
  lanyard:
    image: phineas/lanyard
    build: .
    restart: always
    depends_on:
      - redis
    ports:
      - ${APP_PORT:-4001}:4001
    environment:
      BOT_TOKEN: ${APP_TOKEN}
      REDIS_URL: redis://redis:6379
    links:
      - redis
    networks:
      - internal
      - web

volumes:
  lanyard_presence_data:

networks:
  web:
    driver: bridge
  internal:
    driver: bridge
